/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.day1;

/**
 *
 * @author Jordi B
 */
public class ToggleButton extends javax.swing.JFrame {

    /**
     * Creates new form ToggleButton
     */
    public ToggleButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPriceInstallation = new javax.swing.JLabel();
        jLabelPriceTraining = new javax.swing.JLabel();
        jLabelPricePower = new javax.swing.JLabel();
        jTextPanelUser = new javax.swing.JTextPane();
        jLabelFinalPrice = new javax.swing.JLabel();
        jToggleButtonInstallation = new javax.swing.JToggleButton();
        jToggleButtonTraining = new javax.swing.JToggleButton();
        jToggleButtonPower = new javax.swing.JToggleButton();
        jButtonCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Base Price");

        jLabelPriceInstallation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPriceInstallation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPriceInstallation.setText("60");

        jLabelPriceTraining.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPriceTraining.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPriceTraining.setText("100");

        jLabelPricePower.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPricePower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPricePower.setText("250");

        jTextPanelUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelFinalPrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelFinalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFinalPrice.setText("0€");

        jToggleButtonInstallation.setBackground(new java.awt.Color(191, 243, 255));
        jToggleButtonInstallation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonInstallation.setText("Instalacion");
        jToggleButtonInstallation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonInstallationActionPerformed(evt);
            }
        });

        jToggleButtonTraining.setBackground(new java.awt.Color(191, 243, 255));
        jToggleButtonTraining.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonTraining.setText("Formacion");
        jToggleButtonTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTrainingActionPerformed(evt);
            }
        });

        jToggleButtonPower.setBackground(new java.awt.Color(191, 243, 255));
        jToggleButtonPower.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonPower.setText("Corriente");
        jToggleButtonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPowerActionPerformed(evt);
            }
        });

        jButtonCalculate.setBackground(new java.awt.Color(239, 239, 239));
        jButtonCalculate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCalculate.setText("Calcular");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonInstallation, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPriceInstallation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPriceTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPricePower, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(281, 281, 281))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFinalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextPanelUser)
                            .addComponent(jButtonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextPanelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPriceInstallation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonInstallation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPriceTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPricePower, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void calcular(){
        double precio = 0;

        try{
            precio = Double.parseDouble(jTextPanelUser.getText()); 
            
            if(jToggleButtonInstallation.isSelected()){
                precio += 60;
            }
            if(jToggleButtonTraining.isSelected()){
                precio += 100;
            }
            if(jToggleButtonPower.isSelected()){
                precio += 250;
            }
            
            String texto = String.valueOf(precio);
            
            jLabelFinalPrice.setText(texto + " €");
            
        }catch(Exception e){
            jLabelFinalPrice.setText("Error");
        }
    }
    
    private void jToggleButtonInstallationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonInstallationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonInstallationActionPerformed

    private void jToggleButtonTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTrainingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTrainingActionPerformed

    private void jToggleButtonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPowerActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToggleButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToggleButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFinalPrice;
    private javax.swing.JLabel jLabelPriceInstallation;
    private javax.swing.JLabel jLabelPricePower;
    private javax.swing.JLabel jLabelPriceTraining;
    private javax.swing.JTextPane jTextPanelUser;
    private javax.swing.JToggleButton jToggleButtonInstallation;
    private javax.swing.JToggleButton jToggleButtonPower;
    private javax.swing.JToggleButton jToggleButtonTraining;
    // End of variables declaration//GEN-END:variables
}
